// ─── 菜單資料 ───────────────────────────────────────────────
export const menuItems = [
  {
    id: 1,
    name: "挪威鮭魚飯",
    desc: "高蛋白質・EPA&DHA・ω-3 不飽和脂肪酸，預防心血管疾病",
    price: 220,
    category: "fish",
    badge: "人氣招牌",
    image: "/images/menu-salmon.jpg",
  },
  {
    id: 2,
    name: "招牌雞腿排飯",
    desc: "去骨雞腿使用獨門醬料醃製，再用小火慢煎而成",
    price: 120,
    category: "chicken",
    badge: "人氣招牌",
    image: "/images/menu-chicken.jpg",
  },
  {
    id: 3,
    name: "煎辣味雞腿排飯",
    desc: "秘傳辛香料醃製入味，再用慢火嫩煎而成",
    price: 130,
    category: "chicken",
    badge: "人氣招牌",
    image: "/images/menu-spicy-chicken.jpg",
  },
  {
    id: 4,
    name: "冬瓜肉飯盒",
    desc: "前腿瘦肉搭配綿軟冬瓜煮的肉燥飯，懷念阿嬤的味道",
    price: 80,
    category: "pork",
    badge: null,
    image: "/images/menu-dongua.jpg",
  },
  {
    id: 5,
    name: "健康菜飯",
    desc: "六樣配菜組合的便當，輕鬆樂活的好選擇，也可做素食",
    price: 95,
    category: "veg",
    badge: "可選素食",
    image: "/images/menu-veg.jpg",
  },
  {
    id: 6,
    name: "煎豬排飯",
    desc: "採用里肌肉，口感軟嫩 Q 彈不乾澀",
    price: 110,
    category: "pork",
    badge: null,
    image: "/images/menu-pork.jpg",
  },
  {
    id: 7,
    name: "秋刀魚飯",
    desc: "平價美味健康的魚類首選",
    price: 110,
    category: "fish",
    badge: null,
    image: "/images/menu-saury.jpg",
  },
  {
    id: 8,
    name: "薄鹽鯖魚飯",
    desc: "富含 ω-3 不飽和脂肪酸，是你血管的清道夫",
    price: 170,
    category: "fish",
    badge: null,
    image: "/images/menu-mackerel.jpg",
  },
  {
    id: 9,
    name: "大比目魚飯",
    desc: "俗稱扁鱈，肉質鮮嫩入口即化",
    price: 170,
    category: "fish",
    badge: null,
    image: "/images/menu-halibut.jpg",
  },
];

export const menuCategories = [
  { key: "all", label: "全部" },
  { key: "fish", label: "魚類" },
  { key: "chicken", label: "雞肉" },
  { key: "pork", label: "豬肉" },
  { key: "veg", label: "蔬食" },
];

// ─── 超級食物資料 ────────────────────────────────────────────
export const superfoods = [
  { id: 1, name: "豆類", tag: "植物蛋白", desc: "蛋白質與維生素 B 群的豐富來源，是素食者補充營養的最佳選擇。" },
  { id: 2, name: "藍莓類", tag: "抗氧化", desc: "超級抗氧化劑，富含花青素，有助於對抗自由基、保護細胞健康。" },
  { id: 3, name: "青花椰菜", tag: "鐵質", desc: "素食者的鐵質主力來源，同時含有豐富的維生素 C 與葉酸。" },
  { id: 4, name: "燕麥類", tag: "控糖", desc: "降低膽固醇與血糖的功臣，β-葡聚糖有助於穩定血糖、增加飽足感。" },
  { id: 5, name: "南瓜", tag: "護眼", desc: "富含類胡蘿蔔素（α＋β），有助於護眼、提升免疫力、保護皮膚。" },
  { id: 6, name: "柳橙", tag: "維生素C", desc: "維生素豐富，吃比喝更有益。完整果肉保留膳食纖維，助消化吸收。" },
  { id: 7, name: "鮭魚", tag: "好油脂", desc: "提供必需脂肪酸 EPA 與 DHA，有助於保護心血管、維持大腦健康。" },
  { id: 8, name: "黃豆", tag: "植物蛋白", desc: "最佳植物性蛋白質來源，含有人體必需的胺基酸，有助於肌肉修復。" },
  { id: 9, name: "菠菜", tag: "鐵・葉酸", desc: "營養模範生，鐵質、葉酸、鎂、維生素 K 一次到位，適合各年齡層。" },
  { id: 10, name: "茶", tag: "抗癌", desc: "富含兒茶素，降低罹患各種癌症的風險，同時具有抗氧化與抗發炎效果。" },
  { id: 11, name: "番茄", tag: "茄紅素", desc: "富含茄紅素，好處多得說不完——護心、抗癌、護膚、保護前列腺健康。" },
  { id: 12, name: "雞肉", tag: "瘦肉蛋白", desc: "瘦肉蛋白質最豐富，低脂高蛋白，是健身族與體重管理者的首選食材。" },
  { id: 13, name: "堅果", tag: "好脂肪", desc: "不飽和脂肪酸降低膽固醇，富含維生素 E 與礦物質，保護心血管健康。" },
  { id: 14, name: "優格", tag: "益生菌", desc: "益菌強化免疫系統，促進腸道健康，同時補充鈣質與優質蛋白質。" },
];

// ─── 門市資料 ────────────────────────────────────────────────
export const stores = [
  { name: "建國店", region: "taoyuan", address: "桃園市桃園區建國路151號", phone: "03-366-5051" },
  { name: "國強店", region: "taoyuan", address: "桃園市桃園區國強一街178號", phone: "03-369-8851" },
  { name: "廣豐店", region: "taoyuan", address: "桃園市桃園區永福西街96號", phone: "03-366-0518" },
  { name: "南崁店", region: "taoyuan", address: "桃園市蘆竹區中山路102號", phone: "03-312-1051" },
  { name: "大有店", region: "taoyuan", address: "桃園市桃園區大有路469號", phone: "03-355-0518" },
  { name: "南平店", region: "taoyuan", address: "桃園市桃園區南平路386號", phone: "03-316-5051" },
  { name: "龜山店", region: "taoyuan", address: "桃園市龜山區中興路439號", phone: "03-349-5051" },
  { name: "國際店", region: "taoyuan", address: "桃園市桃園區國際路一段1165號", phone: "03-379-2518" },
  { name: "桃園站前店", region: "taoyuan", address: "桃園市桃園區大同路62-1號", phone: "03-331-8851" },
  { name: "南崁忠孝西店", region: "taoyuan", address: "桃園市蘆竹區忠孝西路165號", phone: "03-352-1051" },
  { name: "八德義勇店", region: "taoyuan", address: "桃園市八德區義勇街46號", phone: "03-361-8051" },
  { name: "林口長庚店", region: "taoyuan", address: "桃園市龜山區復興一路212巷15號", phone: "03-397-1051" },
  { name: "北大店", region: "newtaipei", address: "新北市樹林區學成路532號", phone: "02-2680-5251" },
  { name: "新莊中平店", region: "newtaipei", address: "新北市新莊區中平路122號", phone: "02-2276-8851" },
  { name: "新莊後港店", region: "newtaipei", address: "新北市新莊區後港一路38號", phone: "02-2205-5051" },
  { name: "樹林店", region: "newtaipei", address: "新北市樹林區中山路一段109號", phone: "02-2685-1751" },
  { name: "土城學府店", region: "newtaipei", address: "新北市土城區學府路一段106號", phone: "02-2260-5120" },
  { name: "林口店", region: "newtaipei", address: "新北市林口區文化二路一段96巷10號", phone: "02-2608-5751" },
  { name: "板橋中正店", region: "newtaipei", address: "新北市板橋區中正路323號", phone: "02-2272-5051" },
  { name: "板橋陽明店", region: "newtaipei", address: "新北市板橋區陽明街47號", phone: "02-2258-8851" },
  { name: "北大大德店", region: "newtaipei", address: "新北市三峽區大德路182號", phone: "02-8671-0551" },
  { name: "板橋中山店", region: "newtaipei", address: "新北市板橋區中山路二段262號", phone: "02-2956-0251" },
  { name: "土城中央店", region: "newtaipei", address: "新北市土城區中央路二段252號", phone: "02-8261-8851" },
];

export const storeRegions = [
  { key: "all", label: "全部" },
  { key: "taoyuan", label: "桃園市" },
  { key: "newtaipei", label: "新北市" },
];
